{"uuid": "718f056c-88dd-4886-970b-46e142eb2e38", "children": ["5e7dadd6-5534-47eb-90ae-f4911bc230de"], "befores": [{"name": "contacts_api", "status": "broken", "statusDetails": {"message": "TypeError: auth() takes 0 positional arguments but 1 was given\n", "trace": "  File \"/Users/superhin/个人/MonicaApiAutoTest/venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/superhin/个人/MonicaApiAutoTest/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/superhin/个人/MonicaApiAutoTest/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/superhin/个人/MonicaApiAutoTest/conftest.py\", line 125, in contacts_api\n    return Api(token, base_url)\n  File \"/Users/superhin/个人/MonicaApiAutoTest/apis/api.py\", line 7, in __init__\n    super().__init__(token, base_url)\n  File \"/Users/superhin/个人/MonicaApiAutoTest/apis/base_api.py\", line 24, in __init__\n    self.auth()\n"}, "start": 1658143930046, "stop": 1658143930047}], "start": 1658143930046, "stop": 1658143930111}