{"uuid": "ec051efd-2a55-4a5c-a3ef-ca8cac04b673", "children": ["0cf78226-a077-41e8-9884-a09fee83810c"], "befores": [{"name": "db", "status": "broken", "statusDetails": {"message": "ValueError: port should be of type int\n", "trace": "  File \"/Users/superhin/个人/MonicaApiAutoTest/venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/superhin/个人/MonicaApiAutoTest/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/superhin/个人/MonicaApiAutoTest/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/Users/superhin/个人/MonicaApiAutoTest/conftest.py\", line 87, in db\n    return MysqlUtils(host, port, user, password, db)\n  File \"/Users/superhin/个人/MonicaApiAutoTest/utils/mysql_utils.py\", line 7, in __init__\n    self.conn = pymysql.connect(host=host,\n  File \"/Users/superhin/个人/MonicaApiAutoTest/venv/lib/python3.9/site-packages/pymysql/connections.py\", line 290, in __init__\n    raise ValueError(\"port should be of type int\")\n"}, "start": 1656777711232, "stop": 1656777711232}], "start": 1656777711232, "stop": 1656777711329}